// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn1E81STkzID7pt9A4vlIpEJoLcONhytU',
    appId: '1:79627034914:web:3ad46b48649572bf48057b',
    messagingSenderId: '79627034914',
    projectId: 'fir-using-blockchain',
    authDomain: 'fir-using-blockchain.firebaseapp.com',
    databaseURL: 'https://fir-using-blockchain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-using-blockchain.appspot.com',
    measurementId: 'G-94NV4P3MST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeu7DGChrwPR_IU-wiy6FnvtxUIm0lsQc',
    appId: '1:79627034914:android:cffb51352afe514948057b',
    messagingSenderId: '79627034914',
    projectId: 'fir-using-blockchain',
    databaseURL: 'https://fir-using-blockchain-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-using-blockchain.appspot.com',
  );
  await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
  );
}
